version: '3.7'

volumes:
    builder-data: {}

services:
    builder:
        build:
            context: services/php
            target: builder
        depends_on:
            - postgres
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "../../.php-cs-fixer.php:/home/app/.php-cs-fixer.php"
            - "../../castor.php:/home/app/castor.php"
            - "../../.castor:/home/app/.castor"
            - "builder-data:/home/app"
