twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['common/form_theme.html.twig']
    number_format:
        decimals: 2
        decimal_point: '.'
        thousands_separator: ' '
    globals:
        locale_labels: '%locale_labels%'

when@test:
    twig:
        strict_variables: true
