name: Continuous Integration

'on':
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * MON'

permissions:
  contents: read

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      BUILDKIT_PROGRESS: plain
      CI: 1
    steps:
      -
        uses: actions/checkout@v3

      # Setup

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: jolicode/castor

      -
        name: 'Build and start the infrastructure'
        run: 'castor start && sleep 5'

      -
        name: 'Test the infrastructure is working'
        run: |
          set -e
          set -o pipefail
          curl --fail --insecure --silent -H "Host: 3dfollow.test" https://127.0.0.1 | grep "3D Follow"

      -
        name: 'Run tests'
        run: castor qa:phpunit

      -
        name: 'Run PHPStan'
        run: castor qa:phpstan

      -
        name: 'Run PHP-CS-Fixer'
        run: castor qa:phpcsfixer
